# Generated by Django 4.0.3 on 2022-03-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='images/')),
                ('detected_image', models.ImageField(upload_to='images/')),
                ('teeth_score', models.TextField()),
            ],
        ),
    ]
